set(CMAKE_BUILD_TYPE Release)
set(CMAKE_C_FLAGS -O2)
set(CMAKE_CXX_FLAGS -O2)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE NEVER)
set(CMAKE_C_COMPILER /usr/bin/cc)
set(CMAKE_CXX_COMPILER /usr/bin/c++)
find_program(
    ESSENTIAL_HOST_NINJA
    ninja
    PATHS
        "$ENV{ANDROID_HOME}/cmake/3.22.1/bin"
        "$ENV{ANDROID_SDK_ROOT}/cmake/3.22.1/bin"
    NO_DEFAULT_PATH
)
if(NOT ESSENTIAL_HOST_NINJA)
    find_program(ESSENTIAL_HOST_NINJA ninja)
endif()
if(ESSENTIAL_HOST_NINJA)
    set(CMAKE_MAKE_PROGRAM "${ESSENTIAL_HOST_NINJA}" CACHE FILEPATH "" FORCE)
endif()
